-- ==========================================================
-- RunningCoachPro V6 Multiusuario
-- Ejecutar UNA VEZ en Supabase -> SQL Editor
-- ==========================================================

create table if not exists public.rc_profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null,
    goal text not null,
    level text not null,
    days_per_week integer not null check (days_per_week between 3 and 6),
    weekly_km numeric(7,2) not null check (weekly_km > 0),
    has_race boolean not null default false,
    race_date date,
    target_time_sec integer,
    current_distance_km numeric(6,2),
    current_time_sec integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.rc_plan_sessions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    session_date date not null,
    week_no integer not null,
    workout_type text not null,
    workout_name text not null,
    planned_km numeric(7,2) not null default 0,
    target text,
    intensity text,
    description text,
    is_optional boolean not null default false,
    created_at timestamptz not null default now(),
    unique (user_id, session_date)
);

create table if not exists public.rc_workout_logs (
    user_id uuid not null references auth.users(id) on delete cascade,
    session_date date not null,
    plan_session_id bigint references public.rc_plan_sessions(id) on delete set null,
    actual_km numeric(7,2),
    actual_duration_sec integer,
    rpe integer check (rpe between 1 and 10),
    avg_hr integer,
    max_hr integer,
    status text not null default 'COMPLETADO'
        check (status in ('COMPLETADO', 'MODIFICADO', 'OMITIDO')),
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (user_id, session_date)
);

create index if not exists rc_plan_sessions_user_date_idx
    on public.rc_plan_sessions(user_id, session_date);

create index if not exists rc_workout_logs_user_date_idx
    on public.rc_workout_logs(user_id, session_date);

-- --------------------------
-- RLS
-- --------------------------
alter table public.rc_profiles enable row level security;
alter table public.rc_plan_sessions enable row level security;
alter table public.rc_workout_logs enable row level security;

-- Eliminar políticas anteriores de esta V6 si existen
drop policy if exists "rc_profiles_select_own" on public.rc_profiles;
drop policy if exists "rc_profiles_insert_own" on public.rc_profiles;
drop policy if exists "rc_profiles_update_own" on public.rc_profiles;
drop policy if exists "rc_profiles_delete_own" on public.rc_profiles;

drop policy if exists "rc_plan_select_own" on public.rc_plan_sessions;
drop policy if exists "rc_plan_insert_own" on public.rc_plan_sessions;
drop policy if exists "rc_plan_update_own" on public.rc_plan_sessions;
drop policy if exists "rc_plan_delete_own" on public.rc_plan_sessions;

drop policy if exists "rc_logs_select_own" on public.rc_workout_logs;
drop policy if exists "rc_logs_insert_own" on public.rc_workout_logs;
drop policy if exists "rc_logs_update_own" on public.rc_workout_logs;
drop policy if exists "rc_logs_delete_own" on public.rc_workout_logs;

create policy "rc_profiles_select_own"
on public.rc_profiles for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "rc_profiles_insert_own"
on public.rc_profiles for insert
to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "rc_profiles_update_own"
on public.rc_profiles for update
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "rc_profiles_delete_own"
on public.rc_profiles for delete
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "rc_plan_select_own"
on public.rc_plan_sessions for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "rc_plan_insert_own"
on public.rc_plan_sessions for insert
to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "rc_plan_update_own"
on public.rc_plan_sessions for update
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "rc_plan_delete_own"
on public.rc_plan_sessions for delete
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "rc_logs_select_own"
on public.rc_workout_logs for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "rc_logs_insert_own"
on public.rc_workout_logs for insert
to authenticated
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "rc_logs_update_own"
on public.rc_workout_logs for update
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id)
with check ((select auth.uid()) is not null and (select auth.uid()) = user_id);

create policy "rc_logs_delete_own"
on public.rc_workout_logs for delete
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = user_id);

-- Permisos para las operaciones autenticadas.
grant usage on schema public to authenticated;
grant select, insert, update, delete on public.rc_profiles to authenticated;
grant select, insert, update, delete on public.rc_plan_sessions to authenticated;
grant select, insert, update, delete on public.rc_workout_logs to authenticated;
grant usage, select on sequence public.rc_plan_sessions_id_seq to authenticated;

-- No dar acceso público anónimo a las tablas.
revoke all on public.rc_profiles from anon;
revoke all on public.rc_plan_sessions from anon;
revoke all on public.rc_workout_logs from anon;
